
[character]
success_symbol = "[❯](bold green)"

#[line_break]
#disabled = true

[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 15%
threshold = 20 
style = "bold red"

[python]
format = '[(\($virtualenv\) )]($style)'

[conda]
format = '[(\($environment\) )]($style)'
ignore_base = false

[jobs]
disabled = true

[cmd_duration]
disabled = true

[directory]
style = "bold #0FC2E8"
truncation_symbol = ".../"

[git_status]
disabled = true
